AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spelltacular API 

Resources:

  ApiGetSpellings:
    Type: AWS::Serverless::Function
    Properties:
      Handler: spellings-handler.handler
      Runtime: python3.6
      Environment:
        Variables:
          DB_CONNECTION_STRING: 
            Ref: PostgresConnectionString
      Events:
        Api:
          Type: Api
          Properties:
            Path: /spellings
            Method: get
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds:
          - sg-a3440ed8
        SubnetIds:
          - subnet-a7dcd8c0


Parameters:
  PostgresConnectionString:
    Type: String
    NoEcho: true
