AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spelltacular API 

Resources:

  ApiGetSpellings:
    Type: AWS::Serverless::Function
    Properties:
      Handler: spellings-handler.handler
      Runtime: python3.6
      Environment:
        Variables:
          DB_CONNECTION_STRING: 
            Ref: PostgresConnectionString
      Events:
        Api:
          Type: Api
          Properties:
            Path: /spellings
            Method: get
            RestApiId: ApiGateway
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds:
        - sg-a3440ed8
        SubnetIds:
        - subnet-a7dcd8c0

  PermissionsGetSpellings:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ApiGateway
    - ApiGetSpellings
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiGetSpellings
      Principal: apigateway.amazonaws.com

  ApiGetSpellingLists:
    Type: AWS::Serverless::Function
    Properties:
      Handler: spelling-lists-handler.handler
      Runtime: python3.6
      Environment:
        Variables:
          DB_CONNECTION_STRING: 
            Ref: PostgresConnectionString
      Events:
        Api:
          Type: Api
          Properties:
            Path: /spelling-lists
            Method: get
            RestApiId: ApiGateway
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds:
        - sg-a3440ed8
        SubnetIds:
        - subnet-a7dcd8c0

  PermissionsGetSpellingLists:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ApiGateway
    - ApiGetSpellingLists
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiGetSpellingLists
      Principal: apigateway.amazonaws.com

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        info:
          version: 1.0
          title: "spelltacular-apigateway"
        paths:
          "/spellings":
            get:
              security:
              - cognitoAuthorizer: []
              x-amazon-apigateway-integration:
                type: AWS_PROXY
                httpMethod: POST
                uri: 
                  Fn::Sub: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${ApiGetSpellings.Arn}/invocations"
          "/spelling-lists":
            get:
              security:
              - cognitoAuthorizer: []
              x-amazon-apigateway-integration:
                type: AWS_PROXY
                httpMethod: POST
                uri:
                  Fn::Sub: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${ApiGetSpellingLists.Arn}/invocations"
        securityDefinitions:
          cognitoAuthorizer:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: coginito_user_pools
            x-amazon-apigateway-authorizer:
              providerARNs:
              - Fn::Sub: "arn:aws:cognito-idp:eu-west-1:863487117295:userpool/eu-west-1_LDXnJP6z8"
              type: cognito_user_pools

Parameters:
  PostgresConnectionString:
    Type: String
    NoEcho: true
